name: sifter
description: A location-based chat app
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: 
  firebase_database:
  # firebase_functions: ^4.4.0
  cloud_functions:
  firebase_storage: 
  firebase_messaging: ^15.2.5
  giphy_get: 3.6.1
  youtube_player_flutter: 9.1.1
  link_preview_generator:
    path: ./link_preview_generator-main
  flutter_inappwebview: 6.1.5
  record: ^4.4.0
  audioplayers: ^5.0.0
  cached_network_image: ^3.2.0
  visibility_detector: ^0.3.0
  flutter_dotenv: ^5.0.0
  provider: ^6.0.0
  location: ^4.4.0
  http: 1.1.0
  url_launcher: ^6.2.0
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.12
  shared_preferences: ^2.5.3
  flutter_animate: ^4.5.2
  google_mobile_ads: ^6.0.0
  google_maps_flutter: ^2.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
  